<div class="container">
    <div class="row">
        <div class="wp-testimonial">
            <h2>ADD NEW TESTIMONIAL</h2>
            <form class="form-testimonial" 
            action="<?= $block->escapeUrl($block->getUrl('testimonial/index/save')) ?>" 
            method="post" 
            enctype='multipart/form-data'
            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
            data-mage-init='{"validation":{}}'>
                <div class="col-sm-6 column-left">
                    <div class="form-group">
                        <label for="exampleInputAmount">Your Name</label>
                        <div class="input-group">
                            <div class="input-group-addon"></div>
                            <input type="text" class="form-control" name="name" id="exampleInputAmount" placeholder="Enter your name" data-validate="{required:true}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputAmount">Your Designation</label>
                        <div class="input-group">
                            <div class="input-group-addon"></div>
                            <input type="text" class="form-control" name="designation" id="exampleInputAmount" placeholder="Enter your designation" data-validate="{required:true}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputAmount">Your Message</label>
                        <div class="input-group">
                            <div class="input-group-addon"></div>
                            <input type="text" class="form-control" name="message" id="exampleInputAmount" placeholder="Enter your message" data-validate="{required:true}">
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 column-right">
                    <div class="form-group">
                        <label for="exampleInputAmount">Your Email</label>
                        <div class="input-group">
                            <div class="input-group-addon"></div>
                            <input type="text" class="form-control" name="email" id="exampleInputAmount" placeholder="Enter your email" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputAmount">Your Contact</label>
                        <div class="input-group">
                            <div class="input-group-addon"></div>
                            <input type="text" class="form-control" name="contact" id="exampleInputAmount" placeholder="Enter your contact" data-validate="{required:true}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Your image</label>
                        <input type="file" name="image" id="image" data-validate="{required:true}">
                    </div>
                </div>
                
                <button type="submit" class="btn btn-default">Submit Now</button>
            </form>
        </div>
    </div>
    
</div>
